### ISSUE TITLE
bug: Contributors image not visible

### ISSUE THREAD

**Issue by psankhe28** [elixir-cloud-aai/landing-page#112]
https://elixir-cloud.dcc.sib.swiss/contributors

The contributors' images are not visible.

![image](https://github.com/elixir-cloud-aai/landing-page/assets/84843461/2f8488d2-5e27-4571-80cc-de6f41823df5)

**Comment by JaeAeich** [comment]
Hey @psankhe28 the images are there, can you check again? I can see them on my end maybe. If they are visible let's close the issue :slightly_smiling_face:

**Comment by psankhe28** [comment]
I'm unable to view the images using both Brave and Chrome browsers. . Strangely, I can see the images when accessing them on localhost.

**Comment by JaeAeich** [comment]
Hmm, closing the issue till it's reported again then.
![image](https://github.com/elixir-cloud-aai/landing-page/assets/100477031/7e30b363-a9bc-40b6-a275-016a1d24ffcc)
