### ISSUE TITLE
fix: Slack link expired

### ISSUE THREAD

**Issue by psankhe28** [elixir-cloud-aai/landing-page#113]
The slack mentioned on the website has expired

![image](https://github.com/elixir-cloud-aai/landing-page/assets/84843461/bbbd76ef-87f4-4a95-9074-8bd6036e21d6)

**Comment by JaeAeich** [comment]
@uniqueg is there an update link?

**Comment by uniqueg** [comment]
Thanks @psankhe28 - feel like creating a PR to update the link? :)

**Comment by psankhe28** [comment]
Yeah, I will do it.
