### ISSUE TITLE
style: footer alignment in mobile view

### ISSUE THREAD

**Issue by psankhe28** [elixir-cloud-aai/landing-page#114]
The footer items in the mobile view are currently neither left-aligned nor centered. We have the option to either align them to the left or center them.

![image](https://github.com/elixir-cloud-aai/landing-page/assets/84843461/35ea2d95-3f10-4971-a358-3e66073db1cc)

Should I proceed with left-aligning them, or centering them?

**Comment by JaeAeich** [comment]
@psankhe28 yeah, please go ahead.
