### ISSUE TITLE
style: Twitter tweets in light mode

### ISSUE THREAD

**Issue by psankhe28** [elixir-cloud-aai/landing-page#115]
The grey font color in light mode is not visible. It appears as black in localhost but not in the deployed version.

![image](https://github.com/elixir-cloud-aai/landing-page/assets/84843461/8481b22e-61cc-49ef-850f-a6626bc47230)

**Comment by Sanyam2000-dot** [comment]
Indeed in the dev branch, it appears alright. Please have a look below.
<img width="1440" alt="Screenshot 2024-02-28 at 1 43 16 AM" src="https://github.com/elixir-cloud-aai/landing-page/assets/53525430/0cddae86-946a-42e5-878c-24472a800763">
