### ISSUE TITLE
feat: add "No result found" to all searches

### ISSUE THREAD

**Issue by anantJjain** [elixir-cloud-aai/landing-page#123]
**Is your feature request related to a problem? Please describe.**
Currently the Contributors page shows a "No contributors" message and a "Reset" button when the corresponding search(contributor) is not available but this functionality is not available in search boxes of other pages for e.g. Partners,Funding & Solutions.

**Describe the solution you'd like**
Implementing similar functionality in Partners,Funding and Solutions pages.

**Additional context**
Kindly refer to the video below for more insights : 

https://github.com/elixir-cloud-aai/landing-page/assets/75206987/de40943c-ed9c-40ea-bb87-de2549ba01f9

**Comment by uniqueg** [comment]
Thanks @anantJjain :pray:

I have assigned you for the issue. Please let me know if you'd rather not work on this issue.

**Comment by anantJjain** [comment]
Sure @uniqueg ,I'll take this up.
