### ISSUE TITLE
Search & filter contributors

### ISSUE THREAD

**Issue by uniqueg** [elixir-cloud-aai/landing-page#15]
Once we add all contributors it will be difficult to find indivdiual people. It would therefore be nice to add a Search box (like for the [Project](https://elixir-cloud.dcc.sib.swiss/products) page) to search for names. It would also be nice if one could filter the list by the different positions, e.g., one would only want to see people who are "GA4GH Driver Project Champion"s. For that, one should get a list of _all_ known positions and then create a filter view for those (e.g., a dropdown list or a button for each position)

**Comment by uniqueg** [comment]
To add on to the filtering:
- It would probably be good to have a way to show only active contributors; these would be all that do not have the "Past contributor" position, but there will not be a specific position "Active"
- Likewise, it would be good to have a way to show only project leads; these would be the people with the position "GA4GH Driver Project Champion", but it would be better/clearer to name these "Project leads" in the filter view
- Positions should probably be split up into "Affiliation" and "Role"; you can see the (currently) available entries for each in columns A and B, respectively, of the "Positions" tab in the Google Sheet that you used to fill in your details (name, profile pic URL, email etc.)
- It would probably be good to set these apart in the filter view, e.g., you could have a checkbox each for "Show only active contributors" and "Show only project leads", then another field/button "Filter by affiliation", where we could then have a drop down or group of buttons for all available affiliations, and then finally a field/button "Filter by role", where we could list the roles; for the affiliations, users should be able to select only one, for the roles users should be able to select multiple
- Filters should add up, i.e., if I check the checkboxes for active contributors and project leads and then select, say, "ELIXIR Finland" as affiliation, only active project leads affiliated with ELIXIR Finland should be shown

**Comment by tanya17-05** [comment]
Thankyou @uniqueg for the insights. I'll complete the task soon. :)

Sorry for the delayed response. 🙏

**Comment by uniqueg** [comment]
No worries :)
