### ISSUE TITLE
Fix ELIXIR logos in light mode

### ISSUE THREAD

**Issue by uniqueg** [elixir-cloud-aai/landing-page#17]
The letters in the ELIXIR logo should be black/dark in light mode, otherwise they are not visible well. This applies to both the active/selected and inactive state.

See screenshot:
![elixir_logo_light_dark](https://user-images.githubusercontent.com/10855418/198836562-85222acf-757a-49f5-bb77-a096f2b4c142.png)

**Comment by uniqueg** [comment]
Note that this may be a more general problem, because logos are supplied by the page contributors, i.e., they may put _any_ kind of logo.

Not sure what the best solution is. Maybe @git-anurag-hub?

**Comment by git-anurag-hub** [comment]
I don't think we can provide a solution for this. There are some solutions like:
- Giving the shadow to the SVG image for the logo but that will require that contributors provide the (authentic) SVG logos.
- By applying the filter to the logo not sure if that will work though.
The best option will be to have the logo for both dark mode & light more (I think elixir provides both of them).
Or we can just change the color of the background manually. 
@uniqueg

**Comment by uniqueg** [comment]
I am fine with either of the last two options. Easiest is probably using two logos. I haven't seen the logo with black text as an SVG, but it just takes a minute to adapt the white text SVG.

**Comment by uniqueg** [comment]
You were right, ELIXIR provides both. Please find attached.

![ELIXIR_logo_black_text](https://user-images.githubusercontent.com/10855418/199251592-bab543d4-5657-483c-a0fc-93cb041471cb.svg)
![ELIXIR_logo_white_text](https://user-images.githubusercontent.com/10855418/199251596-1213a0ec-ca72-429b-b047-01466188ad30.svg)

**Comment by git-anurag-hub** [comment]
Maybe @tanya17-05 can work & close this issue. :)

**Comment by tanya17-05** [comment]
Sure @git-anurag-hub @uniqueg , I can do it. Can you please assign this task to me?

**Comment by git-anurag-hub** [comment]
Hey @tanya17-05 , Now you can access the dark icon from the schema. It is now fetched from the server by the field name `IconDark`.

**Comment by tanya17-05** [comment]
@git-anurag-hub I cannot access the `IconDark` property of `partners` that should be present as you updated the schema. I guess you might have updated the notion schema for production environment but for development environment, it might be the same as the old one. Can you please check what's the issue?

**Comment by git-anurag-hub** [comment]
Hey @tanya17-05, I can see the changes in the schema from the code level. 
![Screenshot 2022-12-05 at 12 50 07 AM](https://user-images.githubusercontent.com/58766532/205510865-1cf40561-f533-4e12-bb31-a0dbe412bf50.png)
You can see the `IconDark` in the `properties` object of the specific partner object.

**Comment by tanya17-05** [comment]
@git-anurag-hub unexpectedly working now 😅

**Comment by uniqueg** [comment]
![GSoC-Vertical](https://user-images.githubusercontent.com/10855418/211028547-6af55d42-0958-4f7b-b951-56af6bec5fa6.svg)
