### ISSUE TITLE
Content get hidden in the mobile view

### ISSUE THREAD

**Issue by git-anurag-hub** [elixir-cloud-aai/landing-page#47]
Due to the addition of the banner on the website, the content on the top of the page gets hidden. This is the case only in the mobile view.

![Screenshot 2022-12-06 at 2 52 08 PM](https://user-images.githubusercontent.com/58766532/205871375-6765b78b-4639-4de9-b657-c617b43daf67.png)

**Comment by tanya17-05** [comment]
@git-anurag-hub are you working on this? If not, I can. :)

**Comment by git-anurag-hub** [comment]
Sure @tanya17-05 !
