### ISSUE TITLE
ci: CD workflow for dev deployment

### ISSUE THREAD

**Issue by uniqueg** [elixir-cloud-aai/landing-page#57]
We now have a new development deployment at: https://elixir-landing-page-dev.rahtiapp.fi/

Add a CD workflow that automatically deploys to that site whenever a feature branch is merged into the `dev` branch (which is now the default branch). The built site can then be inspected before being merged into the `main` branch (which will trigger a build of the production website at https://elixir-cloud.dcc.sib.swiss/).

The workflow should:
- Build the page (can use current workflow)
- Publish the image on https://hub.docker.com/orgs/elixircloud (make sure the Notion token/secret is not exposed)
- Update deployment at https://elixir-landing-page-dev.rahtiapp.fi/

**Comment by jemaltahir** [comment]
Thank you @uniqueg . I will be working on this issue.

**Comment by Socuz** [comment]
Hello,

I pushed my work on a new branch called github-actions.
I use secrets from GitHub for Docker, OpenShift and Notion, here is the list:
- DOCKERHUB_USERNAME
- DOCKERHUB_TOKEN
- NOTION_TOKEN
- OPENSHIFT_SERVER
- OPENSHIFT_TOKEN
- OPENSHIFT_NAMESPACE

We need to add those secrets in the settings of the repo.

To have a permanent token on OpenShift, a service account named "gha" has been created. You can retrieve its token with this command:
`oc sa get-token gha`
This token can be used to push on the rahti registry as well.

**Comment by uniqueg** [comment]
Awesome - thanks @Socuz!

A `NOTION_TOKEN` secret is already defined for the repository.

We also already have the following organization-wide secrets defined:
![image](https://user-images.githubusercontent.com/10855418/223415086-750df1d6-043c-4884-a623-53f6669a5c02.png)

So perhaps you could rename `DOCKERHUB_USERNAME` to `DOCKERHUB_LOGIN` (for the login) and `DOCKERHUB_ORG` (for the push, pull and tag)?

Regarding the OpenShift secrets, I have some questions, I will contact you privately.

**Comment by uniqueg** [comment]
All secrets are set now.
