### ISSUE TITLE
Show affiliation next to name on contributors page

### ISSUE THREAD

**Issue by uniqueg** [elixir-cloud-aai/landing-page#62]
Affiliations were moved from the `Position` field to a new field `Affiliation` on the Notion page used as a source for the cards on the [contributors page](https://elixir-cloud.dcc.sib.swiss/contributors).

Affiliations should be shown on the same line as the contributor name, but with a smaller gray font, just like the positions/roles.

Here is what it could look like:
![contributor_card](https://user-images.githubusercontent.com/10855418/210141279-9f1eec42-6fc5-4e8b-b02d-a11682b9c255.png)

**Comment by samyak-max** [comment]
Hi @uniqueg, for this issue do we need to make a notion dev account? I tried to follow the readme, but don't have access to the page.

**Comment by uniqueg** [comment]
The problem with Notion is that I don't want to pay for it, because I don't know where I can get the funding for it and I don't wanna pay for it myself. So I'm using a free account which is very limited. Anyway, to implement this, you don't need to have access to Notion. You just need to know the structure of the data (property names and types) we are dealing with.

I think this screenshot should hopefully give you the required info:

![image](https://user-images.githubusercontent.com/10855418/213441285-9fec547f-d711-4d67-91b0-225e36561a12.png)

The types are:
* Checkbox
* Select
* Text
* Text
* URL
* Text
* Text
* Multi-select
* Relation
* Text
* Text
* Text

in the order of the screenshot.

**Comment by uniqueg** [comment]
Resolved by #88
