### ISSUE TITLE
Persist theme of the website

### ISSUE THREAD

**Issue by git-anurag-hub** [elixir-cloud-aai/landing-page#85]
Right now if we reload the website reloads with the default config i.e. with the light mode. 

We can persist the theme of the website by storing the theme of the page in local storage/cookie so that on the reload or revisits the user sees the website with the persisted theme. On the initial render we can use the system theme mode as the default theme for the website.

**Comment by pandyamarut** [comment]
@git-anurag-hub  
Hi. Looks like I can have a solution for this. Can you please get me started? 

Thanks

**Comment by pandyamarut** [comment]
@git-anurag-hub  @uniqueg  

Hi Folks, 
I have my PR ready, I want to push my code. How Can I get the access to  push my code to this repository?

**Comment by git-anurag-hub** [comment]
@pandyamarut Open a new pr from the branch you are on to the dev & tag me or Alex for the code review!

**Comment by uniqueg** [comment]
Resolved by #86
